# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0033_auto_20160531_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='alarm_condition',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='fault',
            name='fault_name',
            field=models.CharField(default='name', max_length=64, primary_key=True, serialize=False),
        ),
    ]
