# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0034_auto_20160531_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='override_function_role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fault',
            name='override_reporting_entity_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fault',
            name='override_reporting_entity_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fault',
            name='override_source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fault',
            name='override_source_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='fault',
            name='fault_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
