# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0035_auto_20160531_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='override_function_role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='measurement',
            name='override_reporting_entity_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='measurement',
            name='override_reporting_entity_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='measurement',
            name='override_source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='measurement',
            name='override_source_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mobileflow',
            name='override_function_role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mobileflow',
            name='override_reporting_entity_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mobileflow',
            name='override_reporting_entity_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mobileflow',
            name='override_source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mobileflow',
            name='override_source_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='syslog',
            name='override_function_role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='syslog',
            name='override_reporting_entity_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='syslog',
            name='override_reporting_entity_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='syslog',
            name='override_source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='syslog',
            name='override_source_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
